project_id = "orbzcbnhljpriwuvxsjr"

[functions.collect-balance-payments]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.keep-alive]
verify_jwt = false

[functions.system-health-check]
verify_jwt = false

[functions.check-session-status]
verify_jwt = false

[functions.process-refund]
verify_jwt = false