/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackerAccessTokenRouteImport } from './routes/tracker.$accessToken'
import { Route as EventsNewRouteImport } from './routes/events.new'
import { Route as UpdatePaymentBookingTokenIndexRouteImport } from './routes/update-payment.$bookingToken.index'
import { Route as EventsEventIdIndexRouteImport } from './routes/events.$eventId.index'
import { Route as UpdatePaymentBookingTokenConfirmedRouteImport } from './routes/update-payment.$bookingToken.confirmed'
import { Route as EventsEventIdSettingsRouteImport } from './routes/events.$eventId.settings'
import { Route as EventsEventIdPricingRouteImport } from './routes/events.$eventId.pricing'
import { Route as EventsEventIdPaymentsRouteImport } from './routes/events.$eventId.payments'
import { Route as EventsEventIdGuestsRouteImport } from './routes/events.$eventId.guests'
import { Route as EventsEventIdEditRouteImport } from './routes/events.$eventId.edit'
import { Route as EventsEventIdBookingsRouteImport } from './routes/events.$eventId.bookings'
import { Route as BookEventSlugSectionSlugRouteImport } from './routes/book.$eventSlug.$sectionSlug'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as EventsEventIdSectionsSectionIdRouteImport } from './routes/events.$eventId.sections.$sectionId'
import { Route as BookEventSlugSectionSlugConfirmationRouteImport } from './routes/book.$eventSlug.$sectionSlug.confirmation'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackerAccessTokenRoute = TrackerAccessTokenRouteImport.update({
  id: '/tracker/$accessToken',
  path: '/tracker/$accessToken',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsNewRoute = EventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatePaymentBookingTokenIndexRoute =
  UpdatePaymentBookingTokenIndexRouteImport.update({
    id: '/update-payment/$bookingToken/',
    path: '/update-payment/$bookingToken/',
    getParentRoute: () => rootRouteImport,
  } as any)
const EventsEventIdIndexRoute = EventsEventIdIndexRouteImport.update({
  id: '/events/$eventId/',
  path: '/events/$eventId/',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatePaymentBookingTokenConfirmedRoute =
  UpdatePaymentBookingTokenConfirmedRouteImport.update({
    id: '/update-payment/$bookingToken/confirmed',
    path: '/update-payment/$bookingToken/confirmed',
    getParentRoute: () => rootRouteImport,
  } as any)
const EventsEventIdSettingsRoute = EventsEventIdSettingsRouteImport.update({
  id: '/events/$eventId/settings',
  path: '/events/$eventId/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdPricingRoute = EventsEventIdPricingRouteImport.update({
  id: '/events/$eventId/pricing',
  path: '/events/$eventId/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdPaymentsRoute = EventsEventIdPaymentsRouteImport.update({
  id: '/events/$eventId/payments',
  path: '/events/$eventId/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdGuestsRoute = EventsEventIdGuestsRouteImport.update({
  id: '/events/$eventId/guests',
  path: '/events/$eventId/guests',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdEditRoute = EventsEventIdEditRouteImport.update({
  id: '/events/$eventId/edit',
  path: '/events/$eventId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdBookingsRoute = EventsEventIdBookingsRouteImport.update({
  id: '/events/$eventId/bookings',
  path: '/events/$eventId/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const BookEventSlugSectionSlugRoute =
  BookEventSlugSectionSlugRouteImport.update({
    id: '/book/$eventSlug/$sectionSlug',
    path: '/book/$eventSlug/$sectionSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdSectionsSectionIdRoute =
  EventsEventIdSectionsSectionIdRouteImport.update({
    id: '/events/$eventId/sections/$sectionId',
    path: '/events/$eventId/sections/$sectionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const BookEventSlugSectionSlugConfirmationRoute =
  BookEventSlugSectionSlugConfirmationRouteImport.update({
    id: '/confirmation',
    path: '/confirmation',
    getParentRoute: () => BookEventSlugSectionSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events/new': typeof EventsNewRoute
  '/tracker/$accessToken': typeof TrackerAccessTokenRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/book/$eventSlug/$sectionSlug': typeof BookEventSlugSectionSlugRouteWithChildren
  '/events/$eventId/bookings': typeof EventsEventIdBookingsRoute
  '/events/$eventId/edit': typeof EventsEventIdEditRoute
  '/events/$eventId/guests': typeof EventsEventIdGuestsRoute
  '/events/$eventId/payments': typeof EventsEventIdPaymentsRoute
  '/events/$eventId/pricing': typeof EventsEventIdPricingRoute
  '/events/$eventId/settings': typeof EventsEventIdSettingsRoute
  '/update-payment/$bookingToken/confirmed': typeof UpdatePaymentBookingTokenConfirmedRoute
  '/events/$eventId/': typeof EventsEventIdIndexRoute
  '/update-payment/$bookingToken/': typeof UpdatePaymentBookingTokenIndexRoute
  '/book/$eventSlug/$sectionSlug/confirmation': typeof BookEventSlugSectionSlugConfirmationRoute
  '/events/$eventId/sections/$sectionId': typeof EventsEventIdSectionsSectionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events/new': typeof EventsNewRoute
  '/tracker/$accessToken': typeof TrackerAccessTokenRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/book/$eventSlug/$sectionSlug': typeof BookEventSlugSectionSlugRouteWithChildren
  '/events/$eventId/bookings': typeof EventsEventIdBookingsRoute
  '/events/$eventId/edit': typeof EventsEventIdEditRoute
  '/events/$eventId/guests': typeof EventsEventIdGuestsRoute
  '/events/$eventId/payments': typeof EventsEventIdPaymentsRoute
  '/events/$eventId/pricing': typeof EventsEventIdPricingRoute
  '/events/$eventId/settings': typeof EventsEventIdSettingsRoute
  '/update-payment/$bookingToken/confirmed': typeof UpdatePaymentBookingTokenConfirmedRoute
  '/events/$eventId': typeof EventsEventIdIndexRoute
  '/update-payment/$bookingToken': typeof UpdatePaymentBookingTokenIndexRoute
  '/book/$eventSlug/$sectionSlug/confirmation': typeof BookEventSlugSectionSlugConfirmationRoute
  '/events/$eventId/sections/$sectionId': typeof EventsEventIdSectionsSectionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events/new': typeof EventsNewRoute
  '/tracker/$accessToken': typeof TrackerAccessTokenRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/book/$eventSlug/$sectionSlug': typeof BookEventSlugSectionSlugRouteWithChildren
  '/events/$eventId/bookings': typeof EventsEventIdBookingsRoute
  '/events/$eventId/edit': typeof EventsEventIdEditRoute
  '/events/$eventId/guests': typeof EventsEventIdGuestsRoute
  '/events/$eventId/payments': typeof EventsEventIdPaymentsRoute
  '/events/$eventId/pricing': typeof EventsEventIdPricingRoute
  '/events/$eventId/settings': typeof EventsEventIdSettingsRoute
  '/update-payment/$bookingToken/confirmed': typeof UpdatePaymentBookingTokenConfirmedRoute
  '/events/$eventId/': typeof EventsEventIdIndexRoute
  '/update-payment/$bookingToken/': typeof UpdatePaymentBookingTokenIndexRoute
  '/book/$eventSlug/$sectionSlug/confirmation': typeof BookEventSlugSectionSlugConfirmationRoute
  '/events/$eventId/sections/$sectionId': typeof EventsEventIdSectionsSectionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events/new'
    | '/tracker/$accessToken'
    | '/api/public/stripe-webhook'
    | '/book/$eventSlug/$sectionSlug'
    | '/events/$eventId/bookings'
    | '/events/$eventId/edit'
    | '/events/$eventId/guests'
    | '/events/$eventId/payments'
    | '/events/$eventId/pricing'
    | '/events/$eventId/settings'
    | '/update-payment/$bookingToken/confirmed'
    | '/events/$eventId/'
    | '/update-payment/$bookingToken/'
    | '/book/$eventSlug/$sectionSlug/confirmation'
    | '/events/$eventId/sections/$sectionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/events/new'
    | '/tracker/$accessToken'
    | '/api/public/stripe-webhook'
    | '/book/$eventSlug/$sectionSlug'
    | '/events/$eventId/bookings'
    | '/events/$eventId/edit'
    | '/events/$eventId/guests'
    | '/events/$eventId/payments'
    | '/events/$eventId/pricing'
    | '/events/$eventId/settings'
    | '/update-payment/$bookingToken/confirmed'
    | '/events/$eventId'
    | '/update-payment/$bookingToken'
    | '/book/$eventSlug/$sectionSlug/confirmation'
    | '/events/$eventId/sections/$sectionId'
  id:
    | '__root__'
    | '/'
    | '/events/new'
    | '/tracker/$accessToken'
    | '/api/public/stripe-webhook'
    | '/book/$eventSlug/$sectionSlug'
    | '/events/$eventId/bookings'
    | '/events/$eventId/edit'
    | '/events/$eventId/guests'
    | '/events/$eventId/payments'
    | '/events/$eventId/pricing'
    | '/events/$eventId/settings'
    | '/update-payment/$bookingToken/confirmed'
    | '/events/$eventId/'
    | '/update-payment/$bookingToken/'
    | '/book/$eventSlug/$sectionSlug/confirmation'
    | '/events/$eventId/sections/$sectionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsNewRoute: typeof EventsNewRoute
  TrackerAccessTokenRoute: typeof TrackerAccessTokenRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
  BookEventSlugSectionSlugRoute: typeof BookEventSlugSectionSlugRouteWithChildren
  EventsEventIdBookingsRoute: typeof EventsEventIdBookingsRoute
  EventsEventIdEditRoute: typeof EventsEventIdEditRoute
  EventsEventIdGuestsRoute: typeof EventsEventIdGuestsRoute
  EventsEventIdPaymentsRoute: typeof EventsEventIdPaymentsRoute
  EventsEventIdPricingRoute: typeof EventsEventIdPricingRoute
  EventsEventIdSettingsRoute: typeof EventsEventIdSettingsRoute
  UpdatePaymentBookingTokenConfirmedRoute: typeof UpdatePaymentBookingTokenConfirmedRoute
  EventsEventIdIndexRoute: typeof EventsEventIdIndexRoute
  UpdatePaymentBookingTokenIndexRoute: typeof UpdatePaymentBookingTokenIndexRoute
  EventsEventIdSectionsSectionIdRoute: typeof EventsEventIdSectionsSectionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracker/$accessToken': {
      id: '/tracker/$accessToken'
      path: '/tracker/$accessToken'
      fullPath: '/tracker/$accessToken'
      preLoaderRoute: typeof TrackerAccessTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/new': {
      id: '/events/new'
      path: '/events/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof EventsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/update-payment/$bookingToken/': {
      id: '/update-payment/$bookingToken/'
      path: '/update-payment/$bookingToken'
      fullPath: '/update-payment/$bookingToken/'
      preLoaderRoute: typeof UpdatePaymentBookingTokenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/': {
      id: '/events/$eventId/'
      path: '/events/$eventId'
      fullPath: '/events/$eventId/'
      preLoaderRoute: typeof EventsEventIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/update-payment/$bookingToken/confirmed': {
      id: '/update-payment/$bookingToken/confirmed'
      path: '/update-payment/$bookingToken/confirmed'
      fullPath: '/update-payment/$bookingToken/confirmed'
      preLoaderRoute: typeof UpdatePaymentBookingTokenConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/settings': {
      id: '/events/$eventId/settings'
      path: '/events/$eventId/settings'
      fullPath: '/events/$eventId/settings'
      preLoaderRoute: typeof EventsEventIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/pricing': {
      id: '/events/$eventId/pricing'
      path: '/events/$eventId/pricing'
      fullPath: '/events/$eventId/pricing'
      preLoaderRoute: typeof EventsEventIdPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/payments': {
      id: '/events/$eventId/payments'
      path: '/events/$eventId/payments'
      fullPath: '/events/$eventId/payments'
      preLoaderRoute: typeof EventsEventIdPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/guests': {
      id: '/events/$eventId/guests'
      path: '/events/$eventId/guests'
      fullPath: '/events/$eventId/guests'
      preLoaderRoute: typeof EventsEventIdGuestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/edit': {
      id: '/events/$eventId/edit'
      path: '/events/$eventId/edit'
      fullPath: '/events/$eventId/edit'
      preLoaderRoute: typeof EventsEventIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/bookings': {
      id: '/events/$eventId/bookings'
      path: '/events/$eventId/bookings'
      fullPath: '/events/$eventId/bookings'
      preLoaderRoute: typeof EventsEventIdBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$eventSlug/$sectionSlug': {
      id: '/book/$eventSlug/$sectionSlug'
      path: '/book/$eventSlug/$sectionSlug'
      fullPath: '/book/$eventSlug/$sectionSlug'
      preLoaderRoute: typeof BookEventSlugSectionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/sections/$sectionId': {
      id: '/events/$eventId/sections/$sectionId'
      path: '/events/$eventId/sections/$sectionId'
      fullPath: '/events/$eventId/sections/$sectionId'
      preLoaderRoute: typeof EventsEventIdSectionsSectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$eventSlug/$sectionSlug/confirmation': {
      id: '/book/$eventSlug/$sectionSlug/confirmation'
      path: '/confirmation'
      fullPath: '/book/$eventSlug/$sectionSlug/confirmation'
      preLoaderRoute: typeof BookEventSlugSectionSlugConfirmationRouteImport
      parentRoute: typeof BookEventSlugSectionSlugRoute
    }
  }
}

interface BookEventSlugSectionSlugRouteChildren {
  BookEventSlugSectionSlugConfirmationRoute: typeof BookEventSlugSectionSlugConfirmationRoute
}

const BookEventSlugSectionSlugRouteChildren: BookEventSlugSectionSlugRouteChildren =
  {
    BookEventSlugSectionSlugConfirmationRoute:
      BookEventSlugSectionSlugConfirmationRoute,
  }

const BookEventSlugSectionSlugRouteWithChildren =
  BookEventSlugSectionSlugRoute._addFileChildren(
    BookEventSlugSectionSlugRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsNewRoute: EventsNewRoute,
  TrackerAccessTokenRoute: TrackerAccessTokenRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
  BookEventSlugSectionSlugRoute: BookEventSlugSectionSlugRouteWithChildren,
  EventsEventIdBookingsRoute: EventsEventIdBookingsRoute,
  EventsEventIdEditRoute: EventsEventIdEditRoute,
  EventsEventIdGuestsRoute: EventsEventIdGuestsRoute,
  EventsEventIdPaymentsRoute: EventsEventIdPaymentsRoute,
  EventsEventIdPricingRoute: EventsEventIdPricingRoute,
  EventsEventIdSettingsRoute: EventsEventIdSettingsRoute,
  UpdatePaymentBookingTokenConfirmedRoute:
    UpdatePaymentBookingTokenConfirmedRoute,
  EventsEventIdIndexRoute: EventsEventIdIndexRoute,
  UpdatePaymentBookingTokenIndexRoute: UpdatePaymentBookingTokenIndexRoute,
  EventsEventIdSectionsSectionIdRoute: EventsEventIdSectionsSectionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
