/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsNewRouteImport } from './routes/events.new'
import { Route as EventsEventIdIndexRouteImport } from './routes/events.$eventId.index'
import { Route as EventsEventIdEditRouteImport } from './routes/events.$eventId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsNewRoute = EventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdIndexRoute = EventsEventIdIndexRouteImport.update({
  id: '/events/$eventId/',
  path: '/events/$eventId/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdEditRoute = EventsEventIdEditRouteImport.update({
  id: '/events/$eventId/edit',
  path: '/events/$eventId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events/new': typeof EventsNewRoute
  '/events/$eventId/edit': typeof EventsEventIdEditRoute
  '/events/$eventId/': typeof EventsEventIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events/new': typeof EventsNewRoute
  '/events/$eventId/edit': typeof EventsEventIdEditRoute
  '/events/$eventId': typeof EventsEventIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events/new': typeof EventsNewRoute
  '/events/$eventId/edit': typeof EventsEventIdEditRoute
  '/events/$eventId/': typeof EventsEventIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/events/new' | '/events/$eventId/edit' | '/events/$eventId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/events/new' | '/events/$eventId/edit' | '/events/$eventId'
  id:
    | '__root__'
    | '/'
    | '/events/new'
    | '/events/$eventId/edit'
    | '/events/$eventId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsNewRoute: typeof EventsNewRoute
  EventsEventIdEditRoute: typeof EventsEventIdEditRoute
  EventsEventIdIndexRoute: typeof EventsEventIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/new': {
      id: '/events/new'
      path: '/events/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof EventsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/': {
      id: '/events/$eventId/'
      path: '/events/$eventId'
      fullPath: '/events/$eventId/'
      preLoaderRoute: typeof EventsEventIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/edit': {
      id: '/events/$eventId/edit'
      path: '/events/$eventId/edit'
      fullPath: '/events/$eventId/edit'
      preLoaderRoute: typeof EventsEventIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsNewRoute: EventsNewRoute,
  EventsEventIdEditRoute: EventsEventIdEditRoute,
  EventsEventIdIndexRoute: EventsEventIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
