/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsNewRouteImport } from './routes/events.new'
import { Route as EventsEventIdIndexRouteImport } from './routes/events.$eventId.index'
import { Route as EventsEventIdPaymentsRouteImport } from './routes/events.$eventId.payments'
import { Route as EventsEventIdGuestsRouteImport } from './routes/events.$eventId.guests'
import { Route as EventsEventIdEditRouteImport } from './routes/events.$eventId.edit'
import { Route as BookEventSlugSectionSlugRouteImport } from './routes/book.$eventSlug.$sectionSlug'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as EventsEventIdSectionsSectionIdRouteImport } from './routes/events.$eventId.sections.$sectionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsNewRoute = EventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdIndexRoute = EventsEventIdIndexRouteImport.update({
  id: '/events/$eventId/',
  path: '/events/$eventId/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdPaymentsRoute = EventsEventIdPaymentsRouteImport.update({
  id: '/events/$eventId/payments',
  path: '/events/$eventId/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdGuestsRoute = EventsEventIdGuestsRouteImport.update({
  id: '/events/$eventId/guests',
  path: '/events/$eventId/guests',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdEditRoute = EventsEventIdEditRouteImport.update({
  id: '/events/$eventId/edit',
  path: '/events/$eventId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const BookEventSlugSectionSlugRoute =
  BookEventSlugSectionSlugRouteImport.update({
    id: '/book/$eventSlug/$sectionSlug',
    path: '/book/$eventSlug/$sectionSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdSectionsSectionIdRoute =
  EventsEventIdSectionsSectionIdRouteImport.update({
    id: '/events/$eventId/sections/$sectionId',
    path: '/events/$eventId/sections/$sectionId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events/new': typeof EventsNewRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/book/$eventSlug/$sectionSlug': typeof BookEventSlugSectionSlugRoute
  '/events/$eventId/edit': typeof EventsEventIdEditRoute
  '/events/$eventId/guests': typeof EventsEventIdGuestsRoute
  '/events/$eventId/payments': typeof EventsEventIdPaymentsRoute
  '/events/$eventId/': typeof EventsEventIdIndexRoute
  '/events/$eventId/sections/$sectionId': typeof EventsEventIdSectionsSectionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events/new': typeof EventsNewRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/book/$eventSlug/$sectionSlug': typeof BookEventSlugSectionSlugRoute
  '/events/$eventId/edit': typeof EventsEventIdEditRoute
  '/events/$eventId/guests': typeof EventsEventIdGuestsRoute
  '/events/$eventId/payments': typeof EventsEventIdPaymentsRoute
  '/events/$eventId': typeof EventsEventIdIndexRoute
  '/events/$eventId/sections/$sectionId': typeof EventsEventIdSectionsSectionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events/new': typeof EventsNewRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/book/$eventSlug/$sectionSlug': typeof BookEventSlugSectionSlugRoute
  '/events/$eventId/edit': typeof EventsEventIdEditRoute
  '/events/$eventId/guests': typeof EventsEventIdGuestsRoute
  '/events/$eventId/payments': typeof EventsEventIdPaymentsRoute
  '/events/$eventId/': typeof EventsEventIdIndexRoute
  '/events/$eventId/sections/$sectionId': typeof EventsEventIdSectionsSectionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events/new'
    | '/api/public/stripe-webhook'
    | '/book/$eventSlug/$sectionSlug'
    | '/events/$eventId/edit'
    | '/events/$eventId/guests'
    | '/events/$eventId/payments'
    | '/events/$eventId/'
    | '/events/$eventId/sections/$sectionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/events/new'
    | '/api/public/stripe-webhook'
    | '/book/$eventSlug/$sectionSlug'
    | '/events/$eventId/edit'
    | '/events/$eventId/guests'
    | '/events/$eventId/payments'
    | '/events/$eventId'
    | '/events/$eventId/sections/$sectionId'
  id:
    | '__root__'
    | '/'
    | '/events/new'
    | '/api/public/stripe-webhook'
    | '/book/$eventSlug/$sectionSlug'
    | '/events/$eventId/edit'
    | '/events/$eventId/guests'
    | '/events/$eventId/payments'
    | '/events/$eventId/'
    | '/events/$eventId/sections/$sectionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsNewRoute: typeof EventsNewRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
  BookEventSlugSectionSlugRoute: typeof BookEventSlugSectionSlugRoute
  EventsEventIdEditRoute: typeof EventsEventIdEditRoute
  EventsEventIdGuestsRoute: typeof EventsEventIdGuestsRoute
  EventsEventIdPaymentsRoute: typeof EventsEventIdPaymentsRoute
  EventsEventIdIndexRoute: typeof EventsEventIdIndexRoute
  EventsEventIdSectionsSectionIdRoute: typeof EventsEventIdSectionsSectionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/new': {
      id: '/events/new'
      path: '/events/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof EventsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/': {
      id: '/events/$eventId/'
      path: '/events/$eventId'
      fullPath: '/events/$eventId/'
      preLoaderRoute: typeof EventsEventIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/payments': {
      id: '/events/$eventId/payments'
      path: '/events/$eventId/payments'
      fullPath: '/events/$eventId/payments'
      preLoaderRoute: typeof EventsEventIdPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/guests': {
      id: '/events/$eventId/guests'
      path: '/events/$eventId/guests'
      fullPath: '/events/$eventId/guests'
      preLoaderRoute: typeof EventsEventIdGuestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/edit': {
      id: '/events/$eventId/edit'
      path: '/events/$eventId/edit'
      fullPath: '/events/$eventId/edit'
      preLoaderRoute: typeof EventsEventIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$eventSlug/$sectionSlug': {
      id: '/book/$eventSlug/$sectionSlug'
      path: '/book/$eventSlug/$sectionSlug'
      fullPath: '/book/$eventSlug/$sectionSlug'
      preLoaderRoute: typeof BookEventSlugSectionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/sections/$sectionId': {
      id: '/events/$eventId/sections/$sectionId'
      path: '/events/$eventId/sections/$sectionId'
      fullPath: '/events/$eventId/sections/$sectionId'
      preLoaderRoute: typeof EventsEventIdSectionsSectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsNewRoute: EventsNewRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
  BookEventSlugSectionSlugRoute: BookEventSlugSectionSlugRoute,
  EventsEventIdEditRoute: EventsEventIdEditRoute,
  EventsEventIdGuestsRoute: EventsEventIdGuestsRoute,
  EventsEventIdPaymentsRoute: EventsEventIdPaymentsRoute,
  EventsEventIdIndexRoute: EventsEventIdIndexRoute,
  EventsEventIdSectionsSectionIdRoute: EventsEventIdSectionsSectionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
